public class Events
{
	public const string ON_PVP_QUICK_BATTLE_WAVE_START_CHANGE_LEGION_INDEX = "ON_PVP_QUICK_BATTLE_WAVE_START_CHANGE_LEGION_INDEX";

	public const string ON_PVP_RESULT_ANIM = "ON_PVP_RESULT_ANIM";

	public const string ON_PVP_QUICK_BATTLE_TEAMHEALTH_CHANGE = "ON_PVP_QUICK_BATTLE_TEAMHEALTH_CHANGE";

	public const string ON_PVP_PLAY_WAVE_START_TRANSITION = "ON_PVP_PLAY_WAVE_START_TRANSITION";

	public const string ON_PVP_REPLAY_NEXT_WAVE = "ON_PVP_REPLAY_NEXT_WAVE";

	public const string GAME_ENTER = "GAME_ENTER";

	public const string LOAD_STORIES = "LOAD_STORIES";

	public const string LOAD_STORIES_OPENUI = "LOAD_STORIES_OPENUI";

	public const string BEFORE_ENTER_LEVEL = "BEFORE_ENTER_LEVEL";

	public const string AFTER_ENTER_LEVEL = "AFTER_ENTER_LEVEL";

	public const string BEFORE_LEVEL_COMPLETED = "BEFORE_LEVEL_COMPLETED";

	public const string LEVEL_COMPLETED = "LEVEL_COMPLETED";

	public const string LEVEL_BONUS_CLAIMED = "LEVEL_BONUS_CLAIMED";

	public const string AFTER_LEVEL_BONUS_CLAIMED = "AFTER_LEVEL_BONUS_CLAIMED";

	public const string LEVEL_PROGRESS_UPDATED = "GAME_PROGRESS_UPDATED";

	public const string SUB_LEVEL_CHANGED = "SUB_LEVEL_CHANGED";

	public const string CHAPTER_COMPLETE = "CHAPTER_COMPLETE";

	public const string ATTACK_INSTANCE_CLAIMED_FINAL_PRIZE = "ATTACK_INSTANCE_CLAIMED_FINAL_PRIZE";

	public const string BATTLE_START = "BATTLE_START";

	public const string SPECIAL_LEVEL_BATTLE_START = "SPECIAL_LEVEL_BATTLE_START";

	public const string RESET_REPLAY_CONTEXTS = "DESTROY_BATTLE_CONTEXTS";

	public const string ENTER_STORY_MAIN_LEVEL = "ENTER_STORY_MAIN_LEVEL";

	public const string ENTER_REPLAY_LEVEL = "ENTER_REPLAY_LEVEL";

	public const string USER_LEVEL_UP = "USER_LEVEL_UP";

	public const string USER_GAIN_EXP = "USER_GAIN_EXP";

	public const string DUNGEON_LEVEL_UP = "DUNGEON_LEVEL_UP";

	public const string DUNGEON_GAIN_EXP = "DUNGEON_GAIN_EXP";

	public const string ON_SOLDIER_SELECTED = "ON_SOLDIER_SELECTED";

	public const string GAME_ENTITY_DEAD = "GAME_ENTITY_DEAD";

	public const string LEVEL_FORMATION_CHANGED = "LEVEL_FORMATION_CHANGED";

	public const string GET_RESOURCES = "GET_RESOURCES";

	public const string ON_SOLDIER_GET_EXP = "ON_SOLDIER_GET_EXP";

	public const string WORKERS_ALLOCATION_DISPLAY_CHANGED = "WORKERS_ALLOCATION_DISPLAY_CHANGED";

	public const string PRODUCTION_CONFIG_CHANGED = "PRODUCTION_CONFIG_CHANGED";

	public const string SOLDIER_LEVEL_CHANGED = "SOLDIER_LEVEL_CHANGED";

	public const string SOLDIER_EVOLUTED = "SOLDIER_EVOLUTED";

	public const string SOLDIER_BREAKTHROUGH = "SOLDIER_BREAKTHROUGH";

	public const string SOLDIER_POTENTIAL_UPGRADED = "SOLDIER_POTENTIAL_UPGRADED";

	public const string SOLDIER_LEGEND_ITEM_SLOT_UNLOCKED = "SOLDIER_LEGEND_ITEM_SLOT_UNLOCKED";

	public const string PRODUCT_UPGRADED = "PRODUCT_UPGRADED";

	public const string SOLDIER_SUMMONING = "SOLDIER_SUMMONING";

	public const string ITEM_UPGRADE = "ITEM_UPGRADE";

	public const string TECH_UPGRADED = "TECH_UPGRADED";

	public const string BUILDING_MAX_LEVEL_CHANGED = "BUILDING_MAX_LEVEL_CHANGED";

	public const string BUILDING_START_UPGRADING = "BUILDING_START_UPGRADING";

	public const string BUILDING_UPGRADED = "BUILDING_UPGRADED";

	public const string CAMP_SLOT_UNLOCK = "CAMP_SLOT_UNLOCK";

	public const string BUILDING_UPGRADED_USE_ITEM = "BUILDING_UPGRADED_USE_ITEM";

	public const string BUILDING_CONSTRUCTING_COMPLETE = "BUILDING_CONSTRUCTING_COMPLETE";

	public const string BUILDING_SLOTS_CHANGED = "BUILDING_SLOTS_CHANGED";

	public const string ON_CAMP_ALONE = "ON_CAMP_ALONE";

	public const string STOCK_IS_FULL = "STOCK_IS_FULL";

	public const string STOCK_STATUS_CHANGED = "STOCK_STATUS_CHANGED";

	public const string MORE_RESOURCE_REQUIRED = "MORE_RESOURCE_REQUIRED";

	public const string BATTLE_TIME_CHANGE = "BATTLE_TIME_CHANGE";

	public const string MISSION_COMPLETE = "MISSION_COMPLETE";

	public const string MISSION_PROGRESS_CHANGED = "MISSION_PROGRESS_CHANGED";

	public const string MISSION_CLAIMED = "MISSION_CLAIMED";

	public const string TRIGGER_ACTIVATED = "TRIGGER_ACTIVATED";

	public const string TRIGGER_TIMEOUT = "TRIGGER_TIMEOUT";

	public const string ACTION_PLAY_ANIMATION = "ACTION_PLAY_ANIMATION";

	public const string ACTION_PLAY_BATTLE_REPLAY = "ACTION_PLAY_BATTLE_REPLAY";

	public const string MISSION_PICKED = "MISSION_PICKED";

	public const string CUSTOM_ACTION_FINISH = "CUSTOM_ACTION_FINISH";

	public const string ON_STOCK_CHANGE = "ON_STOCK_CHANGE";

	public const string INTERNAL_STOCK_CHANGE = "INTERNAL_STOCK_CHANGE";

	public const string CONFIRM_STOCK_CHANGE = "CONFIRM_STOCK_CHANGE";

	public const string STORY_REQUEST_TO_BEGIN = "STORY_REQUEST_TO_BEGIN";

	public const string STORY_BEGIN = "STORY_BEGIN";

	public const string STORY_END = "STORY_END";

	public const string STORY_SKIP = "STORY_SKIP";

	public const string SOLDIER_UNLOCKED = "SOLDIER_UNLOCKED";

	public const string PRODUCT_UNLOCKED = "PRODUCT_UNLOCKED";

	public const string CHAPTER_UNLOCKED = "CHAPTER_UNLOCKED";

	public const string CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";

	public const string NEWS_TICKER_PULLED = "NEWS_TICKER_PULLED";

	public const string NEWS_MARQUEE_CONTENT_PULLED = "NEWS_MARQUEE_CONTENT_PULLED";

	public const string MAILS_DATA_PROCESSED = "MAILS_DATA_PROCESSED";

	public const string MAILS_RECEIVED = "MAILS_RECEIVED";

	public const string ON_BONUS_CARDS_POPUP = "ON_BONUS_CARDS_POPUP";

	public const string ON_LEVEL_BONUS_SETTLEMENT_POPUP = "ON_LEVEL_BONUS_SETTLEMENT_POPUP";

	public const string ON_BONUS_CARDS_CONFIRM = "ON_BONUS_CARDS_CONFIRM";

	public const string ON_BONUS_CARDS_SELECT = "ON_BONUS_CARDS_SELECT";

	public const string ON_SCOUT_BTN_CLICK = "ON_SCOUT_BTN_CLICK";

	public const string CAMERA_TO_MAIN_CITY_LEFT = "CAMERA_TO_MAIN_CITY_LEFT";

	public const string CAMERA_TO_MAIN_CITY_RIGHT = "CAMERA_TO_MAIN_CITY_RIGHT";

	public const string TRY_AUTO_LOGIN = "TRY_AUTO_LOGIN";

	public const string WORKSHOP_LIST_SCROLLEND = "WORKSHOP_LIST_SCROLLEND";

	public const string SHOW_INSTRUCTIONS = "SHOW_INSTRUCTIONS";

	public const string APP_PAUSE = "APP_PAUSE";

	public const string APP_FOCUS = "APP_FOCUS";

	public const string APP_QUIT = "APP_QUIT";

	public const string STRONGHOLD_ASSIGNED_OCCUPANT = "STRONGHOLD_ASSIGNED_OCCUPANT";

	public const string ACHIEVEMENT_COMPLETE = "ACHIEVEMENT_COMPLETE";

	public const string ACHIEVEMENT_BONUS_CLAIMED = "ACHIEVEMENT_BONUS_CLAIMED";

	public const string WORKER_STATUS_CHANGED = "WORKER_STATUS_CHANGED";

	public const string WORKER_START_PRODUCE = "WORKDER_START_PRODUCE";

	public const string WOLRDMAP_ON_FOCUS_REGION = "WOLRDMAP_ON_FOCUS_REGION";

	public const string WOLRDMAP_ON_STRONGHOLD_SHOWUP = "WOLRDMAP_ON_STRONGHOLD_SHOWUP";

	public const string FORMATION_UNLOCKED = "FORMATION_UNLOCKED";

	public const string FORMATION_LOCKED = "FORMATION_LOCKED";

	public const string FORMATION_FORCE_UNLOCKED = "FORMATION_FORCE_UNLOCKED";

	public const string FORMATION_FORCE_LOCKED = "FORMATION_FORCE_LOCKED";

	public const string REGION_PROD_PROGRESS_DONE = "REGION_PROD_PROGRESS_DONE";

	public const string REGION_PROD_AUTO_CLAIMED = "REGION_PROD_AUTO_CLAIMED";

	public const string STRONGHOLD_PROD_PROGRESS_DONE = "STRONGHOLD_PROD_PROGRESS_DONE";

	public const string RECRUITING_QUEUE_UPDATED = "RECRUITING_QUEUE_UPDATED";

	public const string INFORM_CAMP_REFUND = "INFORM_CAMP_REFUND";

	public const string ACTIVITY_RESET = "ACTIVITY_RESET";

	public const string PVP_RANK_SCORE_CLAIMED = "PVP_RANK_SCORE_CLAIMED";

	public const string WATCHING_REPLAY = "WATCHING_REPLAY";

	public const string WATCHING_PVP_RANK_REPLAY = "WATCHING_PVP_RANK_REPLAY";

	public const string PVP_RANK_BATTLE_START = "PVP_RANK_BATTLE_START";

	public const string PVP_RANK_BATTLE_START_FAILED = "PVP_RANK_BATTLE_START_FAILED";

	public const string PVP_RANK_GET_BATTLE_RESULT_FAILED = "PVP_RANK_GET_BATTLE_RESULT_FAILED";

	public const string NEW_ORDER_STATS = "NEW_ORDER_STATS";

	public const string LEGEND_ITEM_ENHANCED = "LEGEND_ITEM_ENHANCED";

	public const string LEGEND_ITEM_CHANGED_PROPS = "LEGEND_ITEM_CHANGED_PROPS";

	public const string LEGEND_ITEM_REFORGED = "LEGEND_ITEM_REFORGED";

	public const string ON_LEGEND_ITEMS_CHANGED = "LEGEND_ITEMS_CHANGED";

	public const string BLACKMARKET_TREASURE_BONUS_CLAIMED = "BLACKMARKET_TREASURE_BONUS_CLAIMED";

	public const string ACTIVITY_STATUS_CHANGED = "ACTIVITY_STATUS_CHANGED";

	public const string ACTIVITY_OVER_PERIOD = "ACTIVITY_OVER_PERIOD";

	public const string NEW_SINGLETON_ACTIVITY_RECORD = "NEW_SINGLETON_ACTIVITY_RECORD";

	public const string NEW_FORMATION_SLOT_UNLOCKED = "NEW_FORMATION_SLOT_UNLOCKED";

	public const string ORDER_SHIP_SUCCESS = "ORDER_SHIP_SUCCESS";

	public const string ORDER_SHIP_SUCCESS_WITH_STOREITEM = "ORDER_SHIP_SUCCESS_WITH_STOREITEM";

	public const string RECHARGE_COMBO_BONUS_CLAIMED = "RECHARGE_COMBO_BONUS_CLAIMED";

	public const string LIMIT_TIME_MERCHANDISE_ENABLED = "LIMIT_TIME_MERCHANDISE_ENABLED";

	public const string LIMIT_TIME_MERCHANDISE_EXPIRED = "LIMIT_TIME_MERCHANDISE_EXPIRED";

	public const string LEASEHOLD_REGISTERD = "LEASEHOLD_REGISTERD";

	public const string LEASEHOLD_UNREGISTERD = "LEASEHOLD_UNREGISTERD";

	public const string CHEST_CLAIMED = "CHEST_CLAIMED";

	public const string TIME_MACHINE_LAUNCHED = "TIME_MACHINE_LAUNCHED";

	public const string MAIN_CITY_COM_UNLOCKED = "MAIN_CITY_COM_UNLOCKED";

	public const string PIECES_COMPOUND = "PIECES_COMPOUND";

	public const string ON_RECHARGE = "ON_RECHARGE";

	public const string ON_PURCHASE_STATS = "ON_PURCHASE_STATS";

	public const string NEW_MSG_INCOMING_CLEAR_CHECKED = "NEW_MSG_INCOMING_CLEAR_CHECKED";

	public const string INVALID_SYSTEM_TIME_DETECTED = "INVALID_SYSTEM_TIME_DETECTED";

	public const string STAGING_AREA_POSITIONS_CHANGED = "STAGING_AREA_POSITIONS_CHANGED";

	public const string BUILDING_NEED_PAUSE_PRODUCE = "BUILDING_NEED_PAUSE_PRODUCE";

	public const string BUILDING_NEED_RESUME_PRODUCE = "BUILDING_NEED_RESUME_PRODUCE";

	public const string CHIEFDOM_WARNING = "CHIEFDOM_WARNING";

	public const string NEW_USER_REGISTERED = "NEW_USER_REGISTERED";

	public const string NEW_DAY_LOGIN = "NEW_DAY_LOGIN";

	public const string USER_LOGIN = "USER_LOGIN";

	public const string NEW_USER_INSTALL = "NEW_USER_INSTALL";

	public const string GUEST_USER_BIND_SUCCESS = "GUEST_USER_BIND_SUCCESS";

	public const string GUEST_USER_BIND_FAILED = "GUEST_USER_BIND_FAILED";

	public const string GET_CREDENTIALS = "GET_CREDENTIALS";

	public const string NETWORK_ERROR = "NETWORK_ERROR";

	public const string ON_DAILY_LOGIN_STATS = "ON_DAILY_LOGIN_STATS";

	public const string SET_RANK_UI_MODE = "SET_RANK_UI_MODE";

	public const string GET_PROGRESSBAR_NUM = "GET_PROGRESSBAR_NUM";

	public const string REFRESH_USERNAME = "REFRESH_USERNAME";

	public const string MISSION_EXPIRED = "MISSION_EXPIRED";

	public const string OPEN_PVP_PANEL = "OPEN_PVP_PANEL";

	public const string ON_PUSH_GIFT_BAG_REFRESH = "ON_PUSH_GIFT_BAG_REFRESH";

	public const string ON_PUSH_GIFT_BAG_REFRESH_EXT = "ON_PUSH_GIFT_BAG_REFRESH_EXT";

	public const string NEW_GUIDE_MISSION_PLAY_STORY = "NEW_GUIDE_MISSION_PLAY_STORY";

	public const string NEW_GUIDE_MISSION_SKIP_STORY = "NEW_GUIDE_MISSION_SKIP_STORY";

	public const string NEW_BIE_CARDS_SHOW = "NEW_BIE_CARDS_SHOW";

	public const string ROOKIE_POOL_CONTENT_CLOSED = "ROOKIE_POOL_CONTENT_CLOSED";

	public const string ON_GVG_ISLAND_PANEL_SHOW = "ON_GVG_ISLAND_PANEL_SHOW";

	public const string ON_GVG_LORDOFDREAM_PANEL_SHOW = "ON_GVG_LORDOFDREAM_PANEL_SHOW";

	public const string OPEN_WORKER_OVERVIEW_PANEL = "OPEN_WORKER_OVERVIEW_PANEL";

	public const string NEW_GUIDE_PANEL_SHOW = "NEW_GUIDE_PANEL_SHOW";

	public const string NEW_GUIDE_MISSION_UNDERGOING = "NEW_GUIDE_MISSION_UNDERGOING";

	public const string WATCHING_STORY_MAIN_REPLAY = "WATCHING_STORY_MAIN_REPLAY";

	public const string GET_NEW_GUIDE_MISSION_END = "GET_NEW_GUIDE_MISSION_END";

	public const string UPDATE_GVG_RECORD_WORLD_BOSS_INFO = "UPDATE_GVG_RECORD_WORLD_BOSS_INFO";

	public const string UPDATE_ISLAND_COME_AGAIN_SOLDIERS = "UPDATE_ISLAND_COME_AGAIN_SOLDIERS";

	public const string ISLAND_COME_AGAIN_BACK_BATTLEFIELD = "ISLAND_COME_AGAIN_BACK_BATTLEFIELD";

	public const string ISLAND_COME_AGAIN_UPDATE_FORMATION = "ISLAND_COME_AGAIN_UPDATE_FORMATION";

	public const string ISLAND_COME_AGAIN_UPDATE_CURRNET_PRIZE_POOL = "ISLAND_COME_AGAIN_UPDATE_CURRNET_PRIZE_POOL";

	public const string GVG2_ENTER_ISLAND = "GVG2_ENTER_ISLAND";

	public const string ISLAND_COME_AGAIN_LEGION_CHANGE_CONFIRM = "ISLAND_COME_AGAIN_LEGION_CHANGE_CONFIRM";

	public const string UPDATE_FORGE_LEGENDITEM = "UPDATE_FORGE_LEGENDITEM";

	public const string UPDATE_FORGE_SELECT_LEGENDITEM_LIST = "UPDATE_FORGE_SELECT_LEGENDITEM_LIST";

	public const string SHOW_L_TO_M_PAGE = "SHOW_L_TO_M_PAGE";

	public const string UPDATE_GVG_STOREROOM = "UPDATE_GVG_STOREROOM";

	public const string UPDATE_GVG_STORE_ITEMS = "UPDATE_GVG_STORE_ITEMS";

	public const string CLOSE_GVG_STORE_REFRESH_DIALOG = "CLOSE_GVG_STORE_REFRESH_DIALOG";

	public const string GVG3_TALENT_ACTIVATED = "GVG3_TALENT_ACTIVATED";

	public const string GVG3_ENTER_ISLAND = "GVG3_ENTER_ISLAND";

	public const string USER_PROFILE_CHANGE = "USER_PROFILE_CHANGE";

	public const string PVP_RANK_UPDATE_PROGRESS = "PVP_RANK_UPDATE_PROGRESS";

	public const string DRAW_CARD = "DRAW_CARD";

	public const string DRAW_LEGEND_ITEM = "DRAW_LEGEND_ITEM";

	public const string ON_LEGENDITEM_UPDATE = "ON_LEGENDITEM_UPDATE";

	public const string ON_GVGSTOREHOUSE_STOCK_CHANGE = "ON_GVGSTOREHOUSE_STOCK_CHANGE";

	public const string ON_GVGSTOREHOUSE_STOCK_CHANGE_WITH_REASON = "ON_GVGSTOREHOUSE_STOCK_CHANGE_WITH_REASON";

	public const string SET_UI_TOUCHABLE = "SET_UI_TOUCHABLE";

	public const string GVG3_ON_DEPART_ISLAND = "GVG3_ON_DEPART_ISLAND";

	public const string GVG3_ON_REACH_ISLAND = "GVG3_ON_REACH_ISLAND";

	public const string GVG3_UNLOAD_SHIP_CONTROLLER = "GVG3_UNLOAD_SHIP_CONTROLLER";

	public const string SCREEN_RESIZE = "SCREEN_RESIZE";

	public const string ON_GVG3_IZ_COMPLETED = "ON_GVG3_IZ_COMPLETED";

	public const string ON_BLUEPRINTS_CHANGE = "ON_BLUEPRINTS_CHANGE";

	public const string ON_BLUEPRINTS_IDENTIFY = "ON_BLUEPRINTS_IDENTIFY";

	public const string ON_PVP_TOP_RANK_CHANGE = "ON_PVP_TOP_RANK_CHANGE";

	public const string ON_GVG_STORE_REFRESH_ITEMS = "ON_GVG_STORE_REFRESH_ITEMS";

	public const string CHANGE_GUIDE_FINGER_VISIBLE = "CHANGE_GUIDE_FINGER_VISIBLE";

	public const string FRIENDS_CHAT_SESSION_UPDATE = "FRIENDS_CHAT_SESSION_UPDATE";

	public const string LEGEND_ITEM_FX_SWITCHED = "LEGEND_ITEM_FX_SWITCHED";

	public const string LEGEND_ITEM_MAIN_SWAPPED = "LEGEND_ITEM_MAIN_SWAPPED";

	public const string LEGEND_ITEM_MAIN_SWITCHED = "LEGEND_ITEM_MAIN_SWITCHED";

	public const string LEGEND_ITEM_SWAP_SELECT = "LEGEND_ITEM_SWAP_SELECT";

	public const string LEGEND_ITEM_LOCK_STATE_CHANGED = "LEGEND_ITEM_LOCK_STATE_CHANGED";

	public const string ON_GVG3_BATTLE_PASS_UPGRADE_ADVANCED = "ON_GVG3_BATTLE_PASS_UPGRADE_ADVANCED";

	public const string ON_GVG3_CHECK_INSURANCE_ISLAND = "ON_GVG3_CHECK_INSURANCE_ISLAND";

	public const string GVG3_BRAWL_FIGHT_SET_PASUE = "GVG3_BRAWL_FIGHT_SET_PASUE";

	public const string BRAWL_EVENT_SIGN_UP_CHANGE = "BRAWL_EVENT_SIGN_UP_CHANGE";

	public const string ADD_USEABLE_RETROACTIVE_SIGN_IN_COUNT = "ADD_USEABLE_RETROACTIVE_SIGN_IN_COUNT";

	public const string SPIN_WEEK_ACTIVITY_PROGRESS_CHANGE = "SPIN_WEEK_ACTIVITY_PROGRESS_CHANGE";

	public const string DEBUG_INFO_SWITCH_CHANGED = "DEBUG_INFO_SWITCH_CHANGED";

	public const string BACKUP_PANEL_EXTRA_STATE = "BACKUP_PANEL_EXTRA_STATE";
}
