using System.Collections.Generic;

public class HotUpdateProcessTips
{
	public static Dictionary<string, string> Tips = new Dictionary<string, string>
	{
		{ "TIPS_UPDATE_FAILED_0", "网络异常：下载区域配置文件失败，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_FAILED_1", "网络异常：下载配置文件失败，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_FAILED_2", "网络异常：下载版本文件失败，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_FAILED_9", "网络异常：下载更新检测文件失败，请检查网络情况并重启游戏 " },
		{ "TIPS_UPDATE_FAILED_INIT_FAILED", "初始化程序失败，请重启游戏" },
		{ "TIPS_UPDATE_FAILED_3", "未获取到更新程序，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_SUCESS", "更新成功，请重启游戏" },
		{ "TIPS_UPDATE_CHECKSUM_FAILED", "资源文件校验错误，请重启游戏" },
		{ "TIPS_UPDATE_FAILED_6", "更新时网络异常{0}，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_FAILED_7", "获取更新代码失败，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_FAILED_8", "获取更新代码错误，请检查网络情况并重启游戏" },
		{ "TIPS_UPDATE_FAILED_10", "网络异常，请检查网络设置，下载资源失败：" },
		{ "TIPS_UPDATE_FAILED_10_MIUI13", "网络连接不可用\n\n检测到当前手机系统默认关闭了非该品牌手机联运游戏的网络连接权限，请手工在\n设置 -> 应用设置 -> 应用管理 -> 放置军团 -> 应用信息 -> 联网控制，\n打开网络权限后重启游戏\n\n打开网络权限后如果仍然出现此提示，请检查网络连接是否通畅。" },
		{ "TIPS_UPDATE_CHECK_TEXT_1", "检查空间资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_2", "检查网络资源完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_3", "获取标识" },
		{ "TIPS_UPDATE_CHECK_TEXT_4", "获取网关" },
		{ "TIPS_UPDATE_CHECK_TEXT_5", "创建文件夹" },
		{ "TIPS_UPDATE_CHECK_TEXT_6", "网络异常：获取更新文件失败!" },
		{ "TIPS_UPDATE_CHECK_TEXT_7", "网络异常：获取备用更新文件失败!" },
		{ "TIPS_UPDATE_CHECK_TEXT_8", "校验更新文件" },
		{ "TIPS_UPDATE_CHECK_TEXT_9", "更新本地数据" },
		{ "TIPS_UPDATE_CHECK_TEXT_10", "尝试获取备用网络" },
		{ "TIPS_UPDATE_CHECK_TEXT_11", "尝试获取备用网络失败" },
		{ "TIPS_UPDATE_CHECK_TEXT_12", "本地热更文件为空" },
		{ "TIPS_UPDATE_CHECK_TEXT_13", "获取本地热更文件" },
		{ "TIPS_UPDATE_CHECK_TEXT_14", "获取本地热更文件失败" },
		{ "TIPS_UPDATE_CHECK_TEXT_15", "校验本地热更文件" },
		{ "TIPS_UPDATE_CHECK_TEXT_16", "本地使用热更文件和记录不匹配" },
		{ "TIPS_UPDATE_CHECK_TEXT_17", "校验完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_18", "获取标识完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_19", "检查网络资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_20", "使用默认网络资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_21", "找到网络资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_22", "比较网络资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_23", "使用最优网络资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_24", "已获取网络资源" },
		{ "TIPS_UPDATE_CHECK_TEXT_25", "资源列表加载完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_26", "游戏场景预加载完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_27", "摄像机已就位" },
		{ "TIPS_UPDATE_CHECK_TEXT_28", "字体注册完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_29", "系统初始化完毕" },
		{ "TIPS_UPDATE_CHECK_TEXT_30", "TapTap组件初始化完毕" },
		{ "UpdateBar1", "游戏启动中" },
		{ "UpdateBar2", "正在检查更新资源..." },
		{ "UpdateBar3", "正在检查程序更新..." },
		{ "UpdateBar4", "解压中： {0:N2} %" },
		{ "UpdateBar5", "加载遮罩" },
		{ "UpdateBar6", "加载弹窗" },
		{ "UpdateBar7", "加载确认按钮" },
		{ "UpdateBar8", "秒后自动重启" },
		{ "UpdateBar9", "资源更新中 ：{0:N2} MB /{1:N2} MB" },
		{ "UpdateBar10", "程序更新中 ：{0:N2} %" },
		{ "UpdateBar11", "正在检查更新资源 ：{0:N2} %" },
		{ "TIPS_GET_SERVER_INFO_FAILED", "获取服务器信息失败" },
		{ "TIPS_GET_REGION_INFO_FAILED", "获取区服信息失败" },
		{ "TIPS_INSTALL_RESOURCES", "安装资源" },
		{ "TIPS_FINDING_REGIONURL", "网络搜索中" },
		{ "TIPS_PARSE_REGION", "解析网络地址" },
		{ "TipsBiliBiliSDKInit", "初始化bilibili组件" },
		{ "TipsChannelSDKInit", "初始化{0}组件" }
	};
}
