namespace Shift.Legion.ClientApi.Protocol;

public static class PacketIds
{
	public static int INVALID = 0;

	public static int USER_PING = 1;

	public static int USER_PONG = 1;

	public static int SYNC_TIME = 2;

	public static int SERVER_INFO = 3;

	public static int DEVICE_LOG_REQUEST = 9;

	public static int DEVICE_IDENTIFIER_REQUEST = 10;

	public static int PULL_DATA_REQUEST = 50;

	public static int NEED_RE_LOGIN = 98;

	public static int NEED_RESTART = 99;

	public static int USER_LOGIN_REQUEST = 1001;

	public static int USER_PRELOGIN_CHECK = 1002;

	public static int USER_VERIFY_IDENTITY_REQUEST = 1005;

	public static int USER_VERIFY_IDENTITY_TAPTAP_REQUEST = 1006;

	public static int TEL_VERIFY_CODE_REQUEST = 1007;

	public static int USER_VERIFY_IDENTITY_TAPTAP_V4_REQUEST = 1008;

	public static int USER_VERIFY_IDENTITY_QQGAME_REQUEST = 1009;

	public static int USER_VERIFY_IDENTIFY_BILIBILI_REQUEST = 1010;

	public static int GET_SERVER_STATUS_REQUEST = 1011;

	public static int USER_VERIFY_IDENTIFY_XIPU_REQUEST = 1012;

	public static int USER_DEVICE_INFO_REQUEST = 1090;

	public static int ANNOUNCEMENT_LIST_REQUEST = 2000;

	public static int PLACE_ORDER_REQUEST = 4001;

	public static int CHECK_ORDER_REQUEST = 4002;

	public static int STATS_PURCHASE_REQUEST = 4003;

	public static int QUERY_IAP_RESULT_REQUEST = 4004;

	public static int CHECK_UNSHIP_ORDERS_REQUEST = 4005;

	public static int CHECK_UNSHIP_ORDERS_IOS_REQUEST = 4006;

	public static int SYNC_PENDING_RECEIPTS_REQUEST = 4007;

	public static int CONSUMER_PURCHASE_REQUEST = 4008;

	public static int CHECK_UNSHIP_ORDERS_INTL_REQUEST = 4009;

	public static int MAIL_LIST_REQUEST = 9001;

	public static int MAIL_OPERATION_REQUEST = 9002;

	public static int MAIL_CREATE_REQUEST = 9003;

	public static int USER_ACTION_DOWNLOAD_ARCHIVE_REQUEST = 10000;

	public static int USER_ACTION_SET_AS_NEW_GUIDE_MODE_REQUEST = 10001;

	public static int USER_ACTION_GET_MISSIONOF7FOREIGN_REQUEST = 10002;

	public static int USER_ACTION_GET_MISSIONOF7FOREIGN_BONUS_REQUEST = 10003;

	public static int USER_ACTION_GET_ACCOUNTCREATEDAY_REQUEST = 10004;

	public static int USER_ACTION_ENTER_GAME_REQUEST = 10005;

	public static int USER_ACTION_SEND_CHATMESSAGE = 10143;

	public static int USER_ACTION_GET_UNREADMESSAGE = 10144;

	public static int USER_ACTION_READ_MESSAGE = 10145;

	public static int USER_ACTION_DELETE_CHAT = 10146;

	public static int USER_ACTION_BIND_MOBILE_REQUEST = 10970;

	public static int USER_ACTION_BIND_MOBILE_VERIFY_REQUEST = 10971;

	public static int USER_ACTION_RESET_ARCHIVE_REQUEST = 10980;

	public static int USER_ACTION_CONFIRM_RESET_ARCHIVE_REQUEST = 10981;

	public static int USER_ACTION_PROFILE_CHANGE_NICKNAME = 10910;

	public static int USER_ACTION_PROFILE_CHANGE_AVATAR = 10911;

	public static int USER_ACTION_PROFILE_GET_DECORATIVE_OBJECTS_INFO = 10913;

	public static int USER_ACTION_PROFILE_USE_DECORATIVE_OBJECTS_INFO = 10914;

	public static int USER_ACTION_GET_ACCESSORY_INFO = 10915;

	public static int USER_ACTION_EQUIP_ACCESSORY = 10916;

	public static int USER_ACTION_GET_BBS_KEY = 10998;

	public static int USER_ACTION_CHANGE_WORKSHOP_PRODUCE_CONFIG_REQUEST = 10011;

	public static int USER_ACTION_CHANGE_CAMP_PRODUCE_CONFIG_REQUEST = 10012;

	public static int USER_ACTION_CHANGE_STRONGHOLD_PRODUCE_CONFIG_REQUEST = 10013;

	public static int USER_ACTION_USE_ITEM_REQUEST = 10014;

	public static int USER_ACTION_PIECES_COMPOSITE_REQUEST = 10015;

	public static int USER_ACTION_SOUL_STONE_MAX_COMPOSITE_TO_REQUEST = 10016;

	public static int USER_ACTION_UPGRADE_ITEM_REQUEST = 10017;

	public static int USER_ACTION_UPGRADE_TECHNOLOGY_REQUEST = 10018;

	public static int USER_ACTION_RESET_TECHNOLOGY_REQUEST = 10019;

	public static int USER_ACTION_PLAY_STORY_REQUEST = 10020;

	public static int USER_ACTION_TRIGGER_STORY_REQUEST = 10021;

	public static int USER_ACTION_SKIP_CURRENT_STORY_REQUEST = 10022;

	public static int USER_ACTION_ACTIVATE_STORY_REQUEST = 10023;

	public static int USER_ACTION_CHANGE_FORMATION_REQUEST = 10030;

	public static int USER_ACTION_CHANGE_FORMATION_UNIT_REQUEST = 10031;

	public static int USER_ACTION_UNLOCK_FORMATION_REQUEST = 10032;

	public static int USER_ACTION_SYNC_FORMATION_UNITS_REQUEST = 10033;

	public static int USER_ACTION_SYNC_RANK_FORMATION_UNITS_REQUEST = 10034;

	public static int USER_ACTION_GET_FORMATION_UNITS_OF_RANK_REQUEST = 10035;

	public static int USER_ACTION_SET_FORMATION_UNITS_OF_RANK_REQUEST = 10036;

	public static int USER_ACTION_GET_SELF_RANK_REQUEST = 10037;

	public static int USER_ACTION_GET_RANK_LIST_REQUEST = 10038;

	public static int USER_ACTION_GET_DETAIL_RANK_INFO_REQUEST = 10039;

	public static int USER_ACTION_RANK_ADD_ATTACK_BUFF = 10040;

	public static int USER_ACTION_RANK_ADD_DEFENSE_BUFF = 10041;

	public static int USER_ACTION_RANK_CLEAR_CD = 10042;

	public static int USER_ACTION_GET_PVP_SCORE_RANK_LIST_REQUEST = 10043;

	public static int USER_ACTION_GET_PVP_RANK_BATTLE_RECORDS_REQUEST = 10044;

	public static int USER_ACTION_GET_SIMPLE_PVP_RANK_LIST_REQUEST = 10045;

	public static int USER_ACTION_GET_CURRENT_PVP_RANK_GAME_REQUEST = 10046;

	public static int USER_ACTION_GET_PVP_RANK_SEASON_INFO_REQUEST = 10047;

	public static int USER_ACTION_PVP_RANK_SEASON_CHOOSE_ZONE_REQUEST = 10048;

	public static int USER_ACTION_CLAIM_PVP_RANK_SCORE_REQUEST = 10049;

	public static int USER_ACTION_GET_USER_LIST_REQUEST = 10050;

	public static int USER_ACTION_GET_PVP_RANK_LAST_TURN_LAST_10_SELF_RANK_RECORD_RESULT_REQUEST = 10056;

	public static int USER_ACTION_GET_OFFLINE_YIELD_BONUS_REQUEST = 10095;

	public static int USER_ACTION_STOCK_CHANGED_REQUEST = 10090;

	public static int USER_ACTION_SYNC_PRODUCE_REQUEST = 10091;

	public static int USER_ACTION_SYNC_STOCK = 10092;

	public static int USER_ACTION_SYNC_GVG_PRODUCE = 10093;

	public static int USER_ACTION_GET_COLLECTING_INFO = 10094;

	public static int USER_ACTION_SYNC_WEEKLY_MISSION_SCORE = 10602;

	public static int USER_ACTION_SYNC_DAILY_MISSION_SCORE = 10603;

	public static int USER_ACTION_START_BATTLE_REQUEST = 10101;

	public static int USER_ACTION_GET_BATTLE_RESULT_REQUEST = 10102;

	public static int USER_ACTION_SUBMIT_BATTLE_OPERATION_REQUEST = 10103;

	public static int USER_ACTION_RETREAT_REQUEST = 10104;

	public static int USER_ACTION_REVOKE_BATTLE_REQUEST = 10106;

	public static int USER_ACTION_GET_BATTLE_BONUS_REQUEST = 10105;

	public static int USER_ACTION_CONFIRM_BATTLE_BONUS_REQUEST = 10108;

	public static int USER_ACTION_CHECK_BATTLE_FAIL_PROCESS = 10107;

	public static int USER_ACTION_GET_FORMATION_INFO_REQUEST = 10109;

	public static int USER_ACTION_GET_CHECK_CAN_QUICK_BATTLE_REQUEST = 10113;

	public static int USER_ACTION_START_RANK_BATTLE_REQUEST = 10114;

	public static int USER_ACTION_GET_RANK_BATTLE_RESULT_REQUEST = 10115;

	public static int USER_ACTION_GET_PVP_TOP_TOURNAMENT_FORMATION_REQUEST = 10117;

	public static int USER_ACTION_SET_PVP_TOP_TOURNAMENT_FORMATION_REQUEST = 10118;

	public static int USER_ACTION_GET_PVP_TOP_TOURNAMENT_RECORD_REQUEST = 10119;

	public static int USER_ACTION_DOWNLOAD_BATTLE_REPLAY_REQUEST = 10120;

	public static int USER_ACTION_GET_LEVEL_REPLAYS_REQUEST = 10121;

	public static int USER_ACTION_GET_RECENT_REPLAYS_REQUEST = 10122;

	public static int USER_ACTION_GET_PVP_TOP_TOURNAMENT_RANK_REQUEST = 10123;

	public static int USER_ACTION_GET_PVP_TOP_TOURNAMENT_PLAYERS_INFO_REQUEST = 10124;

	public static int USER_ACTION_GET_PVP_TOP_TOURNAMENT_RECORD_SINGLE_PLAYER_REQUEST = 10125;

	public static int USER_ACTION_GET_PVP_TOP_TOURNAMENT_REPLAY_REQUEST = 10126;

	public static int USER_ACTION_INFORM_WATCHING_REPLAY = 10127;

	public static int USER_ACTION_INFORM_WATCHING_PVP_RANK_REPLAY = 10128;

	public static int USER_ACTION_INFORM_WATCHING_STORY_MAIN_REPLAY = 10129;

	public static int USER_ACTION_UPGRADE_BUILDING_REQUEST = 10201;

	public static int USER_ACTION_FINISH_UPGRADE_BUILDING_REQUEST = 10202;

	public static int USER_ACTION_UNLOCK_REGION_REQUEST = 10210;

	public static int USER_ACTION_CHECK_MISSION_STATUS_REQUEST = 10250;

	public static int USER_ACTION_CHECK_REVIEW_POINT_REQUEST = 10260;

	public static int USER_ACTION_STATS_TAPTAP_REVIEW_REQUEST = 10261;

	public static int USER_ACTION_STATS_REVIEW_REQUEST = 10262;

	public static int USER_ACTION_STATS_APPSTORE_REVIEW_REQUEST = 10264;

	public static int USER_ACTION_UPGRADE_SOLDIER_POTENTIAL_REQUEST = 10300;

	public static int USER_ACTION_SOLDIER_ADD_POTENTIAL_PROGRESS_REQUEST = 10301;

	public static int USER_ACTION_GET_ALL_SOLDIERS_COMBAT_POWER = 10302;

	public static int USER_ACTION_UPGRADE_SOLDIER_EVO_LEVEL_REQUEST = 10310;

	public static int USER_ACTION_DRAW_CARD_REQUEST = 10401;

	public static int USER_ACTION_GET_DRAW_CARD_CNT_REQUEST = 10402;

	public static int USER_ACTION_GET_PVP_RANK_LAST_TURN_RESULT_REQUEST = 10052;

	public static int USER_ACTION_GET_PVP_RANK_LAST_TURN_LAST_DAY_RESULT_REQUEST = 10053;

	public static int USER_ACTION_GET_PVP_RANK_LAST_TURN_LAST_DAY_DETAILS_RESULT_REQUEST = 10054;

	public static int USER_ACTION_GET_PVP_RANK_LAST_TURN_LAST_DAY_SINGLE_PLAYER_RECORD_RESULT_REQUEST = 10055;

	public static int USER_ACTION_MAIN_LEVEL_RETREAT_REQUEST = 10600;

	public static int USER_ACTION_MISSION_CLAIM_REQUEST = 10601;

	public static int USER_ACTION_ACTIVITY_CLAIM_REQUEST = 10701;

	public static int USER_ACTION_GET_STORE_ACTIVITY_ITEMS_REQUEST = 10702;

	public static int USER_ACTION_GET_MISSION_ACTIVITY_STORE_ITEMS_REQUEST = 10703;

	public static int USER_ACTION_ACTIVITY_RESET_REQUEST = 10704;

	public static int USER_ACTION_CHECK_ACTIVITIES_OVER_PERIOD_REQUEST = 10705;

	public static int USER_ACTION_CHECK_ACTIVITIES_AUTO_FILL_REQUEST = 10706;

	public static int USER_ACTION_ACTIVITIES_REVIEW_REQUEST = 10707;

	public static int USER_ACTION_GET_DYNAMIC_DISCOUNT_ACTIVITIES_ITEMS_REQUEST = 10708;

	public static int USER_ACTION_GET_DYNAMIC_SIGNIN_ACTIVITIES_ITEMS_REQUEST = 10709;

	public static int USER_ACTION_GET_DYNAMIC_ACTIVITY_UISHOW_CARD_POOL_REQUEST = 10715;

	public static int USER_ACTION_GET_DYNAMIC_ACTIVITY_WORLD_BOSS_REQUEST = 10716;

	public static int USER_ACTION_GET_DYNAMIC_ACTIVITY_ISLAND_COME_AGAIN_REQUEST = 10717;

	public static int USER_ACTION_GET_DYNAMIC_ACTIVITY_ISLAND_COME_AGAIN_CLAIM_REQUEST = 10718;

	public static int USER_ACTION_DYNAMIC_ACTIVITY_ISLAND_COME_AGAIN_EXCHANGE_MONEY = 10719;

	public static int USER_ACTION_GET_ACTIVITY_NEUTRAL_DUNGEON_REQUEST = 10720;

	public static int USER_ACTION_GET_DYNAMIC_ACTIVITY_NEUTRAL_DUNGEON_REQUEST = 10721;

	public static int USER_ACTION_DYNAMIC_ACTIVITY_ISLAND_COME_AGAIN_CLAIM_MISSIONBONUS_REQUEST = 10722;

	public static int USER_ACTION_WEEKLYBATTLEPASS_ACTIVITY_CLAIM_REQUEST = 10723;

	public static int USER_ACTION_GET_RECALLPLAYERACTIVITY = 10738;

	public static int USER_ACTION_CLAIM_RECALLPLAYERBONUS = 10739;

	public static int USER_ACTION_GET_DYNAMIC_CARDPOOL_ACTIVITY_REQUEST = 10725;

	public static int USER_ACTION_DRAW_CARDPOOL_ACTIVITY_REQUEST = 10726;

	public static int USER_ACTION_CLAIM_CARDPOOL_ACTIVITY_BONUS = 10727;

	public static int USER_ACTION_GET_ACTIVITY_FIRSTANDCONTINUOUS_RECHARGE_REQUEST = 10730;

	public static int USER_ACTION_GET_ACTIVITY_CLAIM_RECHARGE_BONUS_REQUEST = 10731;

	public static int USER_ACTION_GET_ACTIVITY_OUTERTECHGIFT_REQUEST = 10735;

	public static int USER_ACTION_DRAW_OUTERTECH_REQUEST = 10736;

	public static int USER_ACTION_EXCHANGE_OUTERTECH_REQUEST = 10737;

	public static int USER_ACTION_GET_ACTIVITY_TREASURE_LTTR_REQUEST = 10740;

	public static int USER_ACTION_GET_ACTIVITY_CLAIM_TREASURE_LTTR_REQUEST = 10741;

	public static int USER_ACTION_GET_ACTIVITY_SECRETTREASURY_REQUEST = 10742;

	public static int USER_ACTION_CLAIM_ACTIVITY_SECRETTREASURY_RECHARGE_BONUS_REQUEST = 10743;

	public static int USER_ACTION_GET_ACTIVITY_STARKEYSSTORE_REQUEST = 10745;

	public static int USER_ACTION_GET_ACTIVITY_EXCHANGEKEYS_REQUEST = 10746;

	public static int USER_ACTION_GET_ACTIVITY_EXCHANGEBONUSWITHKEY_REQUEST = 10747;

	public static int USER_ACTION_GET_ACTIVITY_STARTKEYSTORENEWPERIOD_REQUEST = 10748;

	public static int USER_ACTION_GET_LEVEL_ENEMY_TEMPLATE_REQUEST = 10710;

	public static int USER_ACTION_GET_DYNAMIC_ACTIVITY_LTTR_ITEMS_REQUEST = 10711;

	public static int USER_ACTION_CLAIM_DYNAMIC_ACTIVITY_LTTR_REQUEST = 10712;

	public static int USER_ACTION_LEGENDITEMBLUEPRINT_GET = 10750;

	public static int USER_ACTION_LEGENDITEM_EVOLVED_BY_BLUEPRINT = 10751;

	public static int USER_ACTION_LEGENDITEM_SELFSELECTION_BLUEPRINT = 10752;

	public static int USER_ACTION_LEGENDITEM_SPECIAL_BLUEPRINT_Config = 10753;

	public static int USER_ACTION_LEGENDITEM_SPECILA_BLUEPRINT_CLAIM = 10754;

	public static int USER_ACTION_GVGMEDALRECORD_REQUEST = 10755;

	public static int USER_ACTION_GVGMEDALRANK_REQUEST = 10756;

	public static int USER_ACTION_LEGENDITEM_LOCK = 10757;

	public static int USER_ACTION_SPLITBLUEPRINT_REQUEST = 10758;

	public static int USER_ACTION_GET_STORE_CONTENT_CONFIG_ACTIVITY = 10760;

	public static int USER_ACTION_GET_OUTERTECH_SPEEDPLAN = 10765;

	public static int USER_ACTION_CLAIM_OUTERTECH_SPEEDPLANGIFT = 10766;

	public static int USER_ACTION_GET_SHADOWDEMONACTIVITY = 10769;

	public static int USER_ACTION_GET_RECALLWELFARE_REQUEST = 10770;

	public static int USER_ACTION_DRAW_RECALLWELFARE_REQUEST = 10771;

	public static int USER_ACTION_CLAIM_RECALLWELFARE_REQUEST = 10772;

	public static int USER_ACTION_EXCHANGE_RECALLWELFARE_REQUEST = 10773;

	public static int USER_ACTION_WAROFREALM_GETINFO_REQUEST = 10790;

	public static int USER_ACTION_WAROFREALM_CLAIMMISSIONBONUS = 10791;

	public static int USER_ACTION_WAROFREALM_LOTTERY = 10792;

	public static int USER_ACTION_WAROFREALM_GET_LOTTERYINFO = 10793;

	public static int USER_ACTION_WAROFREALM_CLAIMRANKBONUS = 10794;

	public static int USER_ACTION_WAROFREALM_GETSTAGERECORD = 10795;

	public static int USER_ACTION_WAROFREALM_GETWARBATTLERECORD = 10796;

	public static int USER_ACTION_GET_WAROFREALM_FORMATION_REQUEST = 10797;

	public static int USER_ACTION_SET_WAROFREALM_FORMATION_REQUEST = 10798;

	public static int USER_ACTION_GET_WAROFREALM_STAGEBATTLERECORD = 10799;

	public static int USER_ACTION_WAROFREALM_REPLAY_REQUEST = 10800;

	public static int USER_ACTION_WAROFREALM_GET_SCOREHISTORY = 10802;

	public static int USER_ACTION_PROFILE_CHANGE_GVGMEDAL = 10912;

	public static int USER_ACTION_UPDATE_SOLDIER_MYTH = 10761;

	public static int USER_ACTION_OPEN_SOLDIER_MYTH = 10762;

	public static int USER_ACTION_CHECK_LEGEND_SLOT = 10763;

	public static int USER_ACTION_GET_GVG_STORE_LIMITED_FORMULAS = 10861;

	public static int USER_ACTION_GET_GVG_STORE_USE_FORMULA = 10862;

	public static int SER_ACTION_GET_GVG_STOREROOM_STOCK_LIMIT = 10863;

	public static int USER_ACTION_GET_GVG_STORE_ITEMS = 10864;

	public static int USER_ACTION_GET_GVG_STORE_GUARANTEED = 10865;

	public static int USER_ACTION_EXCHANGE_GVG_STORE_GUARANTEED_TICKET = 10866;

	public static int USER_ACTION_GET_GVG_STORE_INFO = 10867;

	public static int USER_ACTION_SIGN_IN_CLAIM_REQUEST = 10801;

	public static int USER_ACTION_ACHIEVEMENT_CLAIM_REQUEST = 10901;

	public static int USER_ACTION_LEASEHOLD_DAILY_BONUS_CLAIM_REQUEST = 10110;

	public static int USER_ACTION_PENDING_LOTTERY_CLAIM_REQUEST = 10111;

	public static int USER_CLAIM_VERIFY_IDENTITY_BONUS_REQUEST = 10112;

	public static int USER_ACTION_GET_RECYCLE_PRODUCTS = 10501;

	public static int USER_ACTION_RECYCLE_EXPORT_TO = 10502;

	public static int USER_ACTION_GET_FRIENDS_CAN_EXPORT_RECYCLE = 10503;

	public static int USER_ACTION_GET_RECYCLE_STATS = 10504;

	public static int USER_ACTION_SWITCH_RECYCLE_ENABLE = 10505;

	public static int USER_ACTION_GET_SELF_RECYCLE_STATS = 10506;

	public static int USER_ACTION_GET_RECYCLE_REBATE = 10507;

	public static int USER_ACTION_CLAIM_RECYCLE_REBATE = 10508;

	public static int USER_ACTION_GET_TOTAL_EXPORT_REQUEST = 10509;

	public static int USER_ACTION_SET_INVITED_FROM = 10130;

	public static int USER_ACTION_ACTIVATE_INVITED_WORKER = 10131;

	public static int USER_ACTION_ASSIGN_INVITED_WORKER = 10132;

	public static int USER_ACTION_GET_INVITED_WORKERS = 10133;

	public static int USER_ACTION_CHANGE_INVITING_SLOTS_CONFIG = 10134;

	public static int USER_ACTION_REVIEW_INVITED_WORKERS = 10135;

	public static int USER_ACTION_ADD_FRIEND = 10140;

	public static int USER_ACTION_DELETE_FRIEND = 10141;

	public static int USER_ACTION_GET_FRIENDS = 10142;

	public static int USER_ACTION_GET_TREASUREHUNT_ACTIVITY_PROGRESS = 10150;

	public static int USER_ACTION_ASSIGN_SOLDIER_TO_TREASUREHUNT_ACTIVITY = 10151;

	public static int USER_ACTION_GET_LEGEND_ITEM_ACTIVITY_PROGRESS = 10152;

	public static int USER_ACTION_GET_TREASUREHUNT_BOSS_INSURANCE = 10153;

	public static int USER_ACTION_GET_TREASUREHUNT_ACTIVITY_PRESET_FORMATIONS = 10154;

	public static int USER_ACTION_SET_TREASUREHUNT_ACTIVITY_PRESET_FORMATIONS = 10155;

	public static int USER_ACTION_GET_FRIENDS_APPLY_INFO = 10136;

	public static int USER_ACTION_SEND_FRIENDS_APPLY = 10137;

	public static int USER_ACTION_MODIFY_FRIENDS_APPLY = 10138;

	public static int USER_ACTION_GIFT_REDEEM_PREVIEW = 10160;

	public static int USER_ACTION_GIFT_REDEEM_CLAIM = 10161;

	public static int USER_ACTION_BATTLEPASS_ACTIVITY_CLAIM_REQUEST = 10713;

	public static int USER_ACTION_NEWBIE_GACHA_REQUEST = 10714;

	public static int USER_ACTION_GET_OAID_CERT_PEM = 10997;

	public static int USER_ACTION_GET_USER_PROFILE_URL = 10999;

	public static int USER_ACTION_GVG_GET_WORLDBOSS_INFO = 10651;

	public static int USER_ACTION_GVG_WORLDBOSS_START_BATTLE = 10652;

	public static int USER_ACTION_GVG_WORLDBOSS_GET_BATTLE_RESULT_LIST = 10653;

	public static int USER_ACTION_GVG_WORLDBOSS_RECORD_RANKING = 10654;

	public static int USER_ACTION_GVG_GET_IZ_INFOS = 10655;

	public static int USER_ACTION_GVG_CLAIM_USER_CAMPMISSION = 10656;

	public static int USER_ACTION_GVG_GET_SHIP_RECORDS = 10658;

	public static int USER_ACTION_GVG_GET_WORLDBOSS_KEYINFO = 10659;

	public static int USER_ACTION_GVG_GET_SELF_SHIP_COUNT = 10660;

	public static int USER_ACTION_GVG_WORLDBOSS_RECORD_RANKING2 = 10661;

	public static int USER_ACTION_GVG_ROOM_OPERATION = 10662;

	public static int USER_ACTION_GVGMODE2_CREATE_SHIP_SUMMARY = 10663;

	public static int USER_ACTION_GVGMODE2_SHIP_FILL_UP = 10664;

	public static int USER_ACTION_GVG_ROOM_OPERATION_DISABLED = 10665;

	public static int USER_ACTION_GVGMODE2_SYNC_BATTLECONFIG = 10666;

	public static int USER_ACTION_GVGMODE2_GET_BATTLE_RECORDS = 10669;

	public static int USER_ACTION_GVGMODE2_GET_USER_IZ_BATTLE_SUMMARY = 10670;

	public static int USER_ACTION_GVGMODE3_GET_DESCRIPTIONS = 10680;

	public static int USER_ACTION_GVGMODE3_GET_PROCESS_BY_IZCONFIGID = 10681;

	public static int USER_ACTION_GVGMODE3_GET_RECORD = 10682;

	public static int USER_ACTION_GVGMODE3_BUILD_SHIP = 10683;

	public static int USER_ACTION_GVGMODE3_SHIP_CHANGE_ORDER = 10684;

	public static int USER_ACTION_GVGMODE3_DESTORY_SHIP = 10685;

	public static int USER_ACTION_GVGMODE3_ACCEPT_SHIP = 10686;

	public static int USER_ACTION_GVGMODE3_CHANGE_SHIP_CONFIG = 10687;

	public static int USER_ACTION_GVGMODE3_SIGNUP_ACTION = 10688;

	public static int USER_ACTION_GVGMODE3_JOIN_SHIP_TO_ROOM = 10689;

	public static int USER_ACTION_GVGMODE3_CALIM_SETTLEMENT = 10690;

	public static int USER_ACTION_GVGMODE3_GET_IZSETTLEMENT_RECORD = 10691;

	public static int USER_ACTION_GVGMODE3_CLOSE_LASTIZ = 10692;

	public static int USER_ACTION_GVGMODE3_CLOSE_BATTLE_PASS = 10693;

	public static int USER_ACTION_GVGMODE3_GET_BATTLE_PASS_DATA = 10694;

	public static int USER_ACTION_GVGMODE3_CLAIM_BATTLE_PASS_BONUS = 10695;

	public static int USER_ACTION_GVGMODE3_ROOM_OPERATION_DISABLED = 10696;

	public static int USER_ACTION_GVGMODE3_SAVE_DEFAULT_FORMATION = 10697;

	public static int USER_ACTION_GVGMODE3_LOAD_DEFAULT_FORMATION = 10698;

	public static int USER_ACTION_GET_WeeklyActivity_REQUEST = 10780;

	public static int USER_ACTION_DRAW_SPINWEEKLY_REQUEST = 10781;

	public static int USER_ACTION_EXCHANGE_SPINWEEKLY_REQUEST = 10782;

	public static int USER_ACTION_CLAIM_SPINWEEKLYLOTTERY_REQUEST = 10783;

	public static int USER_ACTION_QQ_CLAIM_REQUEST = 10975;

	public static int USER_ACTION_QQ_INFO_REQUEST = 10976;

	public static int USER_ACTION_QQ_CLAIM_DAWANKA_REQUEST = 10977;

	public static int USER_ACTION_QQ_DAWANKA_INFO_REQUEST = 10978;

	public static int PUSH_CHAT = 11000;

	public static int PUSH_RECALLWELFARE_COMPLETEDMISSION = 11001;

	public static int PUSH_UNLOCK_LEGENDITEM = 11002;

	public static int PUSH_ACTIVE_NEWGACHA_ACTIVITYID = 11003;

	public static int PUSH_WAROFREALM_COMPLETEDMISSION = 11004;

	public static int MODULES_INVENTORY_GET_ALL = 20001;

	public static int MODULES_INVENTORY_RETRIEVE = 20002;

	public static int MODULES_INVENTORY_UPDATE = 20003;

	public static int MODULES_LEGEND_ITEM_CREATE = 21001;

	public static int MODULES_LEGEND_ITEM_RETRIEVE = 21002;

	public static int MODULES_LEGEND_ITEM_UPDATE = 21003;

	public static int MODULES_LEGEND_ITEM_DESTROY = 21004;

	public static int MODULES_LEGEND_ITEM_ALL = 21005;

	public static int MODULES_LEGEND_ITEM_LOCK = 21006;

	public static int MODULES_LEGEND_ITEM_REFORGE_LOCK_PROPERTY = 21007;

	public static int MODULES_LEGEND_ITEM_CHANGE_PROPERTY = 21008;

	public static int MODULES_LEGEND_ITEM_REFORGE = 21009;

	public static int MODULES_LEGEND_ITEM_CONFIRM_REFORGE = 21010;

	public static int MODULES_LEGEND_ITEM_CONFIRM_CHANGE_PROPERTY = 21011;

	public static int MODULES_LEGEND_ITEM_ENHANCEMENT_ENHANCE = 22001;

	public static int MODULES_LEGEND_ITEM_SWAPMAIN = 22002;

	public static int MODULES_LEGEND_ITEM_SWITCHMAIN = 22003;

	public static int MODULES_LEGEND_ITEM_SWITCHFX = 22004;

	public static int MODULES_SOLDIER_EQUIPPED_ITEMS_ALL = 23000;

	public static int MODULES_SOLDIER_WEAR_LEGEND_ITEM = 23001;

	public static int MODULES_SOLDIER_TAKE_OFF_LEGEND_ITEM = 23002;

	public static int MODULES_SOLDIER_ITEM_SLOT_ALL = 24000;

	public static int MODULES_SOLDIER_ITEM_SLOT_UNLOCK = 24001;

	public static int MODULES_VERIFY_N_VALIDATE_DRAW_CARD_TEST = 90001;

	public static int MODULES_VERIFY_N_VALIDATE_RANDOM_LEVEL_TEST = 90002;
}
