namespace Shift.Legion.Common.Enums;

public enum ActivityContentType
{
	Chapter = 0,
	Lottery = 1,
	Store = 2,
	StoreMission = 200,
	MissionSerial = 3,
	Achievement = 4,
	SignInSerial = 5,
	LoopSignInSerial = 6,
	TreasureHunt = 7,
	LimitedTimeTotalRecharge = 8,
	BattlePass = 9,
	NewbieGACHA = 10,
	LimitStore = 11,
	CardPool = 12,
	WorldBoss = 13,
	IslandComeAgain = 14,
	NeutralDungeonInstance = 15,
	NoviceRecharge = 16,
	TreasureHouseRecharge = 17,
	UpCardPool = 18,
	NeutralCardPool = 19,
	GvG3BattlePass = 20,
	StarKeyStore = 21,
	ProgressMission = 22,
	ChallengeMission = 23,
	StoreContentConfig = 28,
	SpinWeek = 30,
	MagicTree = 31,
	SmashEgg = 32,
	OpenChest = 33,
	WeekActPassContent = 34,
	SoliderDevelop = 35,
	GvGStore = 36,
	WarOfRealm = 37
}
